name: Update Doras Links

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *" # Updates daily

env:
    DORAS_USERNAME: "doras" # Set your username here for scheduled runs

jobs:
    update-readme:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Generate Doras Links
              uses: dorasto/github-links@v1.0.5
              with:
                  username: ${{ env.DORAS_USERNAME }}
